// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9nzXavLKG-4ZCzdUH2M7juj46qvTw5vs',
    appId: '1:834300685170:web:ee08b876624770803d4beb',
    messagingSenderId: '834300685170',
    projectId: 'thirteenpointrun',
    authDomain: 'thirteenpointrun.firebaseapp.com',
    storageBucket: 'thirteenpointrun.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkIXNYeJEXGS9UiY9JROaIXoliBndyJeA',
    appId: '1:834300685170:android:a5c5fd226efa0e333d4beb',
    messagingSenderId: '834300685170',
    projectId: 'thirteenpointrun',
    storageBucket: 'thirteenpointrun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj6ZrIEpMtTLVc6Xb4ok1HltXSexpqgKk',
    appId: '1:834300685170:ios:0cfd744c67fa3eeb3d4beb',
    messagingSenderId: '834300685170',
    projectId: 'thirteenpointrun',
    storageBucket: 'thirteenpointrun.appspot.com',
    iosBundleId: 'phantomfox.fitness.thirteenPointRun',
  );
}
